version: '3'

services:
  test-app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # - ~/.ssh:/opt/yijun/.ssh
      - ..:/opt/yijun/code
    command: ["tail -f /dev/null"]
    ports:
      - 5678:8000
    networks:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server
    user: "101:101"
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_USER: username
      CLICKHOUSE_PASSWORD: password
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - clickhouse

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clickhouse_pg_db
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/fs/volumes/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical" #required for MaterializedPostgreSQL
    networks:
      - clickhouse

networks:
  # docker network create clickhouse
  clickhouse:
    external: true


